apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "i18n-messages.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "i18n-messages.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.podAnnotations }}
      {{- toYaml .Values.lables | nindent 8 }}
      {{ end }}
    {{- include "i18n-messages.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if eq .Values.logging.enabled true }}

        - name: filebeat
          configMap:
            name: filebeat-config
        {{ end }}
        - name: application-logs
          emptyDir: { }

        - name: application-config
          configMap:
            name: application-config

      containers:
        {{- if eq .Values.logging.enabled true }}

        - name: filebeats
          image: docker.elastic.co/beats/filebeat:7.6.1
          volumeMounts:
            - name: application-logs
              mountPath: /var/log/onlyone-portal/logs/

            - name: filebeat
              subPath: filebeat.yml
              mountPath: /usr/share/filebeat/filebeat.yml

        {{ end }}

        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: application-logs
              mountPath: /var/log/onlyone-portal/logs/

            - name: application-config
              subPath: application.yml
              mountPath: /usr/local/onlyone-portal/config/application.yml

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: {{ .Values.pod.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.pod.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: {{ .Values.pod.probes.rediness.initialDelaySeconds }}
            periodSeconds: {{ .Values.pod.probes.rediness.periodSeconds }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONFIGURATION_FILE_NAME
              value: application
            - name: CONFIGURATION_FILE_TYPE
              value: yml
            - name: CONFIGURATION_PATH
              value: /usr/local/onlyone-portal/config

            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKey }}

            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretKey }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}

            - name: spring.config.additional-location
              value: /usr/local/onlyone-portal/config/