apiVersion: v1
kind: Service
metadata:
  name: {{ include "family-budget-website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "family-budget-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.familyBudgetWebsite.service.type }}
  ports:
    - port: 8080
      name: http
  selector:
    {{- include "family-budget-website.selectorLabels" . | nindent 4 }}