apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    granted-role:
      account-service: {{ .Values.application.allowedRole }}

    oidcEndSessionUrl: {{ .Values.vauthenticator.baseUrl }}/oidc/logout
    auth.oidcIss: {{ .Values.vauthenticator.baseUrl }}

    postLogoutRedirectUri: {{ .Values.application.baseUrl }}/account/site/index

    spring:
      main:
        lazy-initialization: true

      cache:
        cache-names:
          - account-service-ui.i18n.messages

      session:
        timeout: 30m
        store-type: redis
        redis:
          namespace: account-service-ui:session

      security:
        oauth2:
          client:
            registration:
              client:
                client-id: {{ .Values.application.sso.clientApp.clientId }}
                client-secret: {{ .Values.application.sso.clientApp.clientSecret }}
                client-name: VAuthenticator
                provider: vauthenticator
                scope:
                  - openid
                  - profile
                  - email
                  - i18n-message:reader
                  - admin:reset-password
                redirect-uri: {{ .Values.application.baseUrl }}/account/login/oauth2/code/client
                authorization-grant-type: authorization_code
            provider:
              vauthenticator:
                authorization-uri: {{ .Values.vauthenticator.baseUrl }}/oauth2/authorize
                token-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/token
                user-info-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/userinfo
                user-info-authentication-method: header
                jwk-set-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/jwks
                user-name-attribute: email
      data:
        redis:
          host: {{ .Values.application.redis.host }}



    server:
      port: 8080
      forward-headers-strategy: framework
      servlet:
        context-path: /account
      http2:
        enabled: true
      compression:
        enabled: true
        min-response-size: 1KB

    management:
      server:
        port: 8081
        servlet:
          context-path: /
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        shutdown:
          enabled: true
        health:
          show-details: ALWAYS

    vauthenticator:
      session-management:
        enabled: true
        rp-iframe:
          host: {{ .Values.application.baseUrl }}/account
          polling-rate: {{ .Values.application.sessionManagement.pollingRate }}
          origin: {{ .Values.vauthenticator.baseUrl }}
          logout-uri: /account/logout
      client:
        registrationId: client
      host: {{ .Values.vauthenticator.baseUrl }}
      backChannelHost: {{ .Values.vauthenticator.backChannelBaseUrl }}