apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-service-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    granted-role:
      budget-service: {{ .Values.budgetService.allowedRole }}

    spring:
      profiles:
        active: kubernetes
      data:
        redis:
          host: {{ .Values.budgetService.redis.host }}
      redis:
        host: {{ .Values.budgetService.redis.host }}
      main:
        lazy-initialization: true

      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${vauthenticator.host}/oauth2/jwks

    server:
      port: 8080
      servlet:
        context-path: /
      http2:
        enabled: true
      compression:
        enabled: true
        min-response-size: 1KB

    management:
      server:
        port: 8081
        servlet:
          context-path: /
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        probes:
          enabled: true
        shutdown:
          enabled: true
        health:
          show-details: ALWAYS

    vauthenticator:
      host: {{ .Values.vauthenticator.backChannelBaseUrl }}

    budget-service:
      dynamo-db:
        search-tags:
          table-name: {{ .Values.budgetService.dynamoDb.searchTags.tableName }}
          cache-name: {{ .Values.budgetService.dynamoDb.searchTags.cacheName }}
          cache-ttl: {{ .Values.budgetService.dynamoDb.searchTags.cacheTtl }}
        budget-expense:
          table-name: {{ .Values.budgetService.dynamoDb.budgetExpense.tableName }}
        budget-revenue:
          table-name: {{ .Values.budgetService.dynamoDb.budgetRevenue.tableName }}
    
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: family-budget-website-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    granted-role:
      family-budget-website: {{ .Values.familyBudgetWebsite.allowedRole }}

    oidcEndSessionUrl: {{ .Values.vauthenticator.baseUrl }}/oidc/logout
    auth.oidcIss: {{ .Values.vauthenticator.baseUrl }}

    postLogoutRedirectUri: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget/index

    spring:
      profiles:
        active: kubernetes

      main:
        lazy-initialization: true

      cache:
        cache-names:
          - family-budget-website.i18n.messages

      session:
        timeout: 30m
        store-type: redis
        redis:
          namespace: family-budget-website:session

      security:
        oauth2:
          client:
            registration:
              client:
                client-id: {{ .Values.familyBudgetWebsite.sso.clientApp.clientId }}
                client-secret: {{ .Values.familyBudgetWebsite.sso.clientApp.clientSecret }}
                client-name: VAuthenticator
                provider: vauthenticator
                scope:
                  - openid
                  - profile
                  - email
                  - i18n-message:reader
                  - admin:reset-password
                redirect-uri: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget/login/oauth2/code/client
                authorization-grant-type: authorization_code
            provider:
              vauthenticator:
                authorization-uri: {{ .Values.vauthenticator.baseUrl }}/oauth2/authorize
                token-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/token
                user-info-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/userinfo
                jwk-set-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/jwks
                user-name-attribute: email

      data:
        redis:
          host: {{ .Values.familyBudgetWebsite.redis.host }}

    server:
      port: 8080
      forward-headers-strategy: framework
      servlet:
        context-path: /family-budget
      http2:
        enabled: true
      compression:
        enabled: true
        min-response-size: 1KB

    management:
      server:
        port: 8081
        servlet:
          context-path: /
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        probes:
          enabled: true
        shutdown:
          enabled: true
        health:
          show-details: ALWAYS


    budgetServiceUri: {{ .Values.familyBudgetWebsite.budgetServiceUri }}

    vauthenticator:
      session-management:
        enabled: true
        rp-iframe:
          host: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget
          polling-rate: {{ .Values.familyBudgetWebsite.sessionManagement.pollingRate }}
          origin: {{ .Values.vauthenticator.baseUrl }}
          logout-uri: /family-budget/logout
      client:
        registrationId: client
      host: {{ .Values.vauthenticator.baseUrl }}
      backChannelHost: {{ .Values.vauthenticator.backChannelBaseUrl }}