{{- if eq .Values.logging.enabled true }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Release.Namespace }}
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: true

    filebeat.inputs:
      - type: log
        multiline.pattern: '^java.|^[[:space:]]+(at|\.{3})\b|^Caused by:|^END:'
        multiline.negate: false
        multiline.match: after

        enabled: true
        paths:
          - /var/log/onlyone-portal/logs/*.log

    processors:
      - add_cloud_metadata: ~
      - add_docker_metadata: ~

    setup.kibana:
      host: "{{ .Values.logging.kibana.host }}"

    output.elasticsearch:
      hosts: ['{{ .Values.logging.elasticSearch.host }}']

{{ end }}


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-service-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    granted-role:
      budget-service: {{ .Values.budgetService.allowedRole }}

    logging.file.name: /var/log/onlyone-portal/logs/${spring.application.name}.log


    spring:
      profiles:
        active: kubernetes
      redis:
        host: {{ .Values.budgetService.redis.host }}
      main:
        lazy-initialization: true

      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${vauthenticator.host}/oauth2/jwks

    server:
      port: 8080
      servlet:
        context-path: /
      http2:
        enabled: true
      compression:
        enabled: true
        min-response-size: 1KB

    management:
      server:
        port: 8081
        servlet:
          context-path: /
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        probes:
          enabled: true
        shutdown:
          enabled: true
        health:
          show-details: ALWAYS

    vauthenticator:
      host: {{ .Values.vauthenticator.backChannelBaseUrl }}

    budget-service:
      dynamo-db:
        search-tags:
          table-name: {{ .Values.budgetService.dynamoDb.searchTags.tableName }}
          cache-name: {{ .Values.budgetService.dynamoDb.searchTags.cacheName }}
          cache-ttl: {{ .Values.budgetService.dynamoDb.searchTags.cacheTtl }}
        budget-expense:
          table-name: {{ .Values.budgetService.dynamoDb.budgetExpense.tableName }}
        budget-revenue:
          table-name: {{ .Values.budgetService.dynamoDb.budgetRevenue.tableName }}
    
    
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: family-budget-website-config
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |
    granted-role:
      family-budget-website: {{ .Values.familyBudgetWebsite.allowedRole }}

    endSessionWithoutDiscovery: true
    oidcEndSessionUrl: {{ .Values.vauthenticator.baseUrl }}/oidc/logout
    auth.oidcIss: {{ .Values.vauthenticator.baseUrl }}
    logging.file.name: /var/log/onlyone-portal/logs/${spring.application.name}.log

    postLogoutRedirectUri: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget/index

    spring:
      profiles:
        active: kubernetes

      main:
        lazy-initialization: true

      cache:
        cache-names:
          - family-budget-website.i18n.messages

      session:
        timeout: 30m
        store-type: redis
        redis:
          namespace: family-budget-website:session

      security:
        oauth2:
          client:
            registration:
              client:
                client-id: {{ .Values.familyBudgetWebsite.sso.clientApp.clientId }}
                client-secret: {{ .Values.familyBudgetWebsite.sso.clientApp.clientSecret }}
                client-name: VAuthenticator
                provider: vauthenticator
                scope:
                  - openid
                  - profile
                  - email
                  - i18n-message:reader
                redirect-uri: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget/login/oauth2/code/client
                client-authentication-method: basic
                authorization-grant-type: authorization_code
            provider:
              vauthenticator:
                authorization-uri: {{ .Values.vauthenticator.baseUrl }}/oauth2/authorize
                token-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/token
                user-info-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/userinfo
                user-info-authentication-method: header
                jwk-set-uri: {{ .Values.vauthenticator.backChannelBaseUrl }}/oauth2/jwks
                user-name-attribute: email

      redis:
        host: {{ .Values.familyBudgetWebsite.redis.host }}

      sleuth:
        redis:
          enabled: false

    server:
      port: 8080
      forward-headers-strategy: framework
      servlet:
        context-path: /family-budget
      http2:
        enabled: true
      compression:
        enabled: true
        min-response-size: 1KB

    management:
      server:
        port: 8081
        servlet:
          context-path: /
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        probes:
          enabled: true
        shutdown:
          enabled: true
        health:
          show-details: ALWAYS


    budgetServiceUri: {{ .Values.familyBudgetWebsite.budgetServiceUri }}

    vauthenticator:
      session-management:
        enabled: true
        rp-iframe:
          host: {{ .Values.familyBudgetWebsite.baseUrl }}/family-budget
          polling-rate: {{ .Values.familyBudgetWebsite.sessionManagement.pollingRate }}
          origin: {{ .Values.vauthenticator.baseUrl }}
          logout-uri: /family-budget/logout
      client:
        registrationId: client
      host: {{ .Values.vauthenticator.baseUrl }}
      backChannelHost: {{ .Values.vauthenticator.backChannelBaseUrl }}

    i18n-messages:
      cache:
        updater:
          listener:
            sleeping: {{ .Values.familyBudgetWebsite.i18n.listener.sleeping }}
            queueUrl: {{ .Values.familyBudgetWebsite.i18n.listener.queueUrl }}
            maxNumberOfMessages: {{ .Values.familyBudgetWebsite.i18n.listener.maxNumberOfMessages }}
            visibilityTimeout: {{ .Values.familyBudgetWebsite.i18n.listener.visibilityTimeout }}
            waitTimeSeconds: {{ .Values.familyBudgetWebsite.i18n.listener.waitTimeSeconds }}
      ttl: {{ .Values.familyBudgetWebsite.i18n.ttl }}
      base-url: {{ .Values.familyBudgetWebsite.i18n.baseUrl }}