apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "budget-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.budgetService.replicaCount }}
  selector:
    matchLabels:
  {{- include "budget-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.budgetService.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.budgetService.lables }}
      {{- toYaml .Values.budgetService.lables | nindent 8 }}
      {{ end }}
    {{- include "budget-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.budgetService.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: application-config
          configMap:
            name: budget-service-config

      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: application-config
              subPath: application.yml
              mountPath: /usr/local/onlyone-portal/config/application.yml

          image: "{{ .Values.budgetService.image.repository }}:{{ .Values.budgetService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.budgetService.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: {{ .Values.budgetService.pod.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.budgetService.pod.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: {{ .Values.budgetService.pod.probes.rediness.initialDelaySeconds }}
            periodSeconds: {{ .Values.budgetService.pod.probes.rediness.periodSeconds }}
          resources:
          {{- toYaml .Values.budgetService.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.budgetService.aws.accessKey }}

            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.budgetService.aws.secretKey }}
            - name: AWS_REGION
              value: {{ .Values.budgetService.aws.region }}

            - name: spring.config.additional-location
              value: /usr/local/onlyone-portal/config/