{{if .Values.budgetService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "budget-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.budgetService.ingress.className }}
    {{- with .Values.budgetService.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "budget-service.name" . }}
                port:
                  number: 8080
      host: {{  .Values.budgetService.ingress.host }}
    {{- with .Values.budgetService.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}
  {{end}}
