apiVersion: v1
kind: Service
metadata:
  name: {{ include "budget-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "budget-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.budgetService.service.type }}
  ports:
    - port: 8080
      name: http
  selector:
    {{- include "budget-service.selectorLabels" . | nindent 4 }}