apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "family-budget-website.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.familyBudgetWebsite.replicaCount }}
  selector:
    matchLabels:
  {{- include "family-budget-website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.familyBudgetWebsite.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.familyBudgetWebsite.lables }}
      {{- toYaml .Values.familyBudgetWebsite.lables | nindent 8 }}
      {{ end }}
    {{- include "family-budget-website.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.familyBudgetWebsite.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if eq .Values.logging.enabled true }}

        - name: filebeat
          configMap:
            name: filebeat-config
        {{ end }}
        - name: application-logs
          emptyDir: { }

        - name: application-config
          configMap:
            name: family-budget-website-config

      containers:
        {{- if eq .Values.logging.enabled true }}

        - name: filebeats
          image: docker.elastic.co/beats/filebeat:7.6.1
          volumeMounts:
            - name: application-logs
              mountPath: /var/log/onlyone-portal/logs/

            - name: filebeat
              subPath: filebeat.yml
              mountPath: /usr/share/filebeat/filebeat.yml

        {{ end }}

        - name: family-budget-website
          volumeMounts:
            - name: application-logs
              mountPath: /var/log/onlyone-portal/logs/

            - name: family-budget-website-config
              subPath: application.yml
              mountPath: /usr/local/onlyone-portal/config/application.yml

          image: "{{ .Values.familyBudgetWebsite.image.repository }}:{{ .Values.familyBudgetWebsite.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.familyBudgetWebsite.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: {{ .Values.familyBudgetWebsite.pod.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.familyBudgetWebsite.pod.probes.liveness.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: {{ .Values.familyBudgetWebsite.pod.probes.rediness.initialDelaySeconds }}
            periodSeconds: {{ .Values.familyBudgetWebsite.pod.probes.rediness.periodSeconds }}
          resources:
          {{- toYaml .Values.familyBudgetWebsite.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKey }}

            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretKey }}
            - name: AWS_REGION
              value: {{ .Values.aws.region }}

            - name: spring.config.additional-location
              value: /usr/local/onlyone-portal/config/