apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "family-budget-website.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.familyBudgetWebsite.ingress.className }}
    {{- with .Values.familyBudgetWebsite.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}


spec:
  rules:
    - http:
        paths:
          - path: /family-budget
            pathType: Prefix
            backend:
              service:
                name: {{ include "family-budget-website.name" . }}
                port:
                  number: 8080
      host: {{  .Values.familyBudgetWebsite.ingress.host }}
    {{- with .Values.familyBudgetWebsite.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4}}
    {{- end }}